
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


  0%|          | 0/16 [00:00<?, ?it/s]/home/users/delon/aemulusnu_massfunction/utils.py:36: IntegrationWarning: The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.
  res, err = quad(dσ2dk, 0, np.inf)
/home/users/delon/aemulusnu_massfunction/utils.py:60: IntegrationWarning: The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.
  res, err = quad(dσ2dRdk, 0, np.inf)
  6%|▋         | 1/16 [00:04<01:11,  4.74s/it] 12%|█▎        | 2/16 [00:09<01:06,  4.76s/it] 19%|█▉        | 3/16 [00:14<01:02,  4.78s/it] 25%|██▌       | 4/16 [00:19<00:57,  4.79s/it] 31%|███▏      | 5/16 [00:23<00:52,  4.78s/it] 38%|███▊      | 6/16 [00:28<00:47,  4.78s/it] 44%|████▍     | 7/16 [00:33<00:42,  4.77s/it] 50%|█████     | 8/16 [00:38<00:38,  4.77s/it] 56%|█████▋    | 9/16 [00:42<00:33,  4.77s/it] 62%|██████▎   | 10/16 [00:47<00:28,  4.76s/it] 69%|██████▉   | 11/16 [00:52<00:23,  4.76s/it] 75%|███████▌  | 12/16 [00:57<00:19,  4.76s/it] 81%|████████▏ | 13/16 [01:01<00:14,  4.76s/it] 88%|████████▊ | 14/16 [01:06<00:09,  4.76s/it] 94%|█████████▍| 15/16 [01:11<00:04,  4.75s/it]100%|██████████| 16/16 [01:16<00:00,  4.74s/it]100%|██████████| 16/16 [01:16<00:00,  4.76s/it]
Traceback (most recent call last):
  File "/home/users/delon/aemulusnu_massfunction/fit.py", line 182, in <module>
    inv_weighted_cov = {a:np.linalg.inv(weighted_cov[a]) for a in weighted_cov}  
  File "/home/users/delon/aemulusnu_massfunction/fit.py", line 182, in <dictcomp>
    inv_weighted_cov = {a:np.linalg.inv(weighted_cov[a]) for a in weighted_cov}  
  File "<__array_function__ internals>", line 200, in inv
  File "/home/users/delon/.local/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 532, in inv
    _assert_stacked_2d(a)
  File "/home/users/delon/.local/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 183, in _assert_stacked_2d
    raise LinAlgError('%d-dimensional array given. Array must be '
numpy.linalg.LinAlgError: 0-dimensional array given. Array must be at least two-dimensional
