
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


0it [00:00, ?it/s]1it [00:01,  1.01s/it]2it [00:02,  1.37s/it]3it [00:05,  1.83s/it]4it [00:08,  2.35s/it]5it [00:11,  2.79s/it]6it [00:15,  3.13s/it]7it [00:19,  3.47s/it]8it [00:23,  3.67s/it]8it [00:27,  3.42s/it]
Traceback (most recent call last):
  File "/home/users/delon/aemulusnu_massfunction/prepare_data.py", line 41, in <module>
    assert(len(snapshot_mass)==len(snapshot_Np))
AssertionError
